#! /usr/bin/python3
# requirements.txt file generated by pipreqs .
import pydub, pytube, sys, os

def yt2mp3(url, path):
    path = os.path.abspath(path)
    yt = pytube.YouTube(url)
    streams = yt.streams.filter(only_audio=True)

    # find the highest audio bitrate
    maxBitrate = float("-inf")
    maxIndex = 0 # stream with the highest bitrate to be downloaded
    for s in streams:
        print(f"Found {s.title} with bitrate {s.abr}")
        if float(s.abr.replace("kbps", "")) > maxBitrate:
            maxBitrate = float(s.abr.replace("kbps", ""))
            maxIndex = streams.index(s)

    print(f"Downloading {streams[maxIndex].title} with bitrate {maxBitrate}kbps")

    name, ext = os.path.splitext(streams[maxIndex].download(path))
    if ext != ".mp3":
        pydub.AudioSegment.from_file(name + ext).export(name + ".mp3", format="mp3", bitrate="320k")
        os.remove(name + ext)

    print(f"Downloaded {name}.mp3")

def main():
    url = sys.argv[1]
    if (len(sys.argv) > 2): path = sys.argv[2]
    else: path = os.getcwd()
    yt2mp3(url, path)

if __name__ == "__main__":
    main()
